# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '13.0'

$swap_white_array = ["ZXYModuleC"]

def zxy_swap_pod(name, param1 = '', param2 = {})
  return if !$swap_white_array.include? name
  tag = ''
  options = Hash.new
  if param1.is_a? String
    tag = param1
  elsif param1.is_a? Hash
    options = param1
  end
  options = options.merge param2
  if tag.empty?
    pod name, options
  else
    pod name, tag, options
  end
end

def commonPods
  pod 'ZXYModuleProtocols', :path => './Modules/ZXYModuleProtocols'
  pod 'ZXYDIManager', :path => './Modules/ZXYDIManager'
end

def swapPods
  zxy_swap_pod 'ZXYModuleA', :path => './Modules/ZXYModuleA'
  zxy_swap_pod 'ZXYModuleB', :path => './Modules/ZXYModuleB'
  zxy_swap_pod 'ZXYModuleC', :path => './Modules/ZXYModuleC'
end

target 'HotSwap (iOS)' do
  use_frameworks!
  commonPods
  swapPods
end

target 'HotSwap (macOS)' do
  use_frameworks!
end
